import { useFormik } from "formik";
import Head from "next/head";
import * as Yup from "yup";
import { useState, useMemo } from "react";
import { AgGridReact } from "ag-grid-react";
import defaultColumnDef from "./../components/defaultColumnDef";
import { sideBar } from "./../components/Sidebar";
import { flatten } from "../utils/flatten";
// const rowData = [
//   {
//     folderName: "main",
//     jobTitle: "CEO",
//     employmentType: "Permanent",
//     jobType: "WFO",
//     children: [
//       {
//         dataset: "sub",
//         jobTitle: "VP",
//         employmentType: "Permanent",
//         jobType: "WFO",
//       },
//     ],
//   },
// ];

export default function Home() {
  const [rowData, setRowData] = useState([
    {
      hierarchy: ["folderName"],
      description: "NA",
      product: "NA",
      baseDataLevel: "Personal Account",
    },
    {
      hierarchy: ["folderName", "datasetName"],
      description: "news data",
      product: "NA",
      baseDataLevel: "Personal Account",
    },
  ]);

  const [tags, setTags] = useState([]);
  const [show, setShow] = useState(false);

  const submitButtonHandler = () => {
    setShowFolder(!showfolder);
    const replace = {
      folderName: formik.values.folderName,
      datasetName: formik.values.datasetName,
    };
    const clone = structuredClone(rowData);
    const newData = clone.map((data) => {
      data.description = formik.values.description;
      data.product = formik.values.product || "NA";
      data.baseDataLevel = formik.values.baseDataLevel || "NA";
      data.hierarchy = data.hierarchy.map((o) => {
        return replace[o];
      });
      return data;
    });
    setRowData(() => newData);
  };

  const formik = useFormik({
    initialValues: {
      dataSource: "Upload New Data",
      datasetName: "",
      folderName: "",
      description: "NA",
      uniqueResponse: {
        status: true,
        message: "Unique Dataset Name",
      },
      product: "NA",
      baseDataLevel: "NA",
      nameOfBaseDataLevel: "NA",
      datasetFile: null,
      datasetFileList: [],
      schema: [],
      updatedSchema: [],
      selectedFileIndex: -1,
      divide_cols_by_ref: {},
      datasetModule: "",
      no_of_unique_acc_ids: null,
      activeStep: 0,
    },
    validationSchema: Yup.lazy((values) =>
      Yup.object().shape({
        datasetName: Yup.string().test(
          "datasetName",
          "Dataset name is required",
          (name) => {
            if (values.dataSource === "Upload New Data" && !name) {
              return false;
            } else {
              return true;
            }
          }
        ),
        folderName: Yup.string().test(
          "folderName",
          "folderName name is required",
          (name) => {
            if (!name) {
              return false;
            } else {
              return true;
            }
          }
        ),
        //   datasetFileList: Yup.array().test(
        //     "datasetFileList",
        //     "Dataset is required",
        //     (dataset) => {
        //       if (values.dataSource === "Upload New Data" && !dataset.length) {
        //         return false;
        //       } else {
        //         return true;
        //       }
        //     }
        //   ),
      })
    ),
    onSubmit: submitButtonHandler,
  });

  const folderNameHandler = (e) => {
    formik.setFieldValue("folderName", e.target.value);
  };
  const datasetNameHandler = (e) => {
    formik.setFieldValue("datasetName", e.target.value);
  };

  // for aggrid ::
  const [showfolder, setShowFolder] = useState(false);
  const [gridApi, setGridApi] = useState(null);

  const [columnDefs, setColumnDefs] = useState([
    // we're using the auto group column by default!
    { field: "description" },
    { field: "product" },
    { field: "baseDataLevel" },
  ]);
  const autoGroupColumnDef = {
    headerName: "Folder Name",
    cellRendererParams: {
      suppressCount: true,
    },
  };
  const getDataPath = useMemo(() => {
    return (data) => {
      return data.hierarchy;
    };
  }, []);

  const treeData = true;
  const onGridReady = (params) => {
    setGridApi(params.api);
  };

  // for aggrid ::
  return (
    <div>
      <Head>
        <title>Folder Structure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="tab-content" id="pills-tabContent">
          <div
            className="tab-pane fade show active "
            role="tabpanel"
            aria-labelledby="home-tab"
          >
            <div className="card">
              <div className="card-body">
                <label htmlFor="" className="text-muted">
                  Source of Dataset {formik.values.dataSource}
                </label>
                <div className="row">
                  <div className="col-md-12">
                    <button
                      type="button"
                      className="btn btn-primary btn-large mr-1"
                      onClick={() => setShow(!show)}
                    >
                      Create folder structure
                    </button>
                  </div>
                </div>
                <div className="row">
                  {show && (
                    <div className="col-md-4">
                      <label htmlFor="" className="text-muted">
                        Folder Name <span className="text-danger">*</span>
                      </label>
                      <input
                        className={
                          "form-control" +
                          ((formik.touched?.folderName &&
                            formik.errors?.folderName) ||
                          !formik.values.uniqueResponse?.status
                            ? " is-invalid"
                            : "")
                        }
                        placeholder="Folder Name"
                        type="text"
                        value={formik.values.folderName || ""}
                        onBlur={formik.handleBlur}
                        name="folderName"
                        onChange={folderNameHandler}
                      />
                      {formik.touched.folderName && formik.errors.folderName ? (
                        <span className="text-danger">
                          {formik.errors?.folderName}
                        </span>
                      ) : (
                        formik.touched.folderName &&
                        !formik.values.uniqueResponse?.status && (
                          <span className="text-danger">
                            {formik.values.uniqueResponse?.message}
                          </span>
                        )
                      )}
                    </div>
                  )}
                  <div className="col-md-4">
                    <label htmlFor="" className="text-muted">
                      Dataset Name <span className="text-danger">*</span>
                    </label>
                    <input
                      className={
                        "form-control" +
                        ((formik.touched?.datasetName &&
                          formik.errors?.datasetName) ||
                        !formik.values.uniqueResponse?.status
                          ? " is-invalid"
                          : "")
                      }
                      placeholder="Dataset Name"
                      type="text"
                      value={formik.values.datasetName || ""}
                      onBlur={formik.handleBlur}
                      name="datasetName"
                      onChange={datasetNameHandler}
                    />
                    {formik.touched.datasetName && formik.errors.datasetName ? (
                      <span className="text-danger">
                        {formik.errors?.datasetName}
                      </span>
                    ) : (
                      formik.touched.datasetName &&
                      !formik.values.uniqueResponse?.status && (
                        <span className="text-danger">
                          {formik.values.uniqueResponse?.message}
                        </span>
                      )
                    )}
                  </div>
                  <div className={`${show ? "col-md-4" : "col-md-8"}`}>
                    <label htmlFor="" className="text-muted">
                      Description
                    </label>
                    <input
                      className="form-control"
                      placeholder="Description"
                      type="text"
                      name="description"
                      value={formik.values.description || ""}
                      onChange={formik.handleChange}
                    />
                  </div>
                  <div className="col-md-4">
                    <label htmlFor="" className="text-muted">
                      Belong to Product(s)
                    </label>
                    <div className={"tags-input"}>
                      {/* <ul id="tags">
                        {tags.map((tag, index) => (
                          <li key={index} className="tag">
                            <span className="tag-title">{tag}</span>
                            <span
                              className="tag-close-icon"
                              onClick={() => removeTags(index)}
                            >
                              x
                            </span>
                          </li>
                        ))}
                      </ul> */}
                      <input
                        className="form-control"
                        // className={
                        //   "form-control" +
                        //   ((formik.touched?.datasetName &&
                        //     formik.errors?.datasetName) ||
                        //   !formik.values.uniqueResponse?.status
                        //     ? " is-invalid"
                        //     : "")
                        // }
                        type="text"
                        onKeyUp={(event) =>
                          event.key === "Enter" ? addTags(event) : null
                        }
                        placeholder="Press enter to add products"
                        onKeyPress={(e) => {
                          if (e.key === "Enter") e.preventDefault();
                        }}
                      />
                    </div>
                  </div>
                  <div className="col-md-4">
                    <label htmlFor="" className="text-muted">
                      Base Data Level
                    </label>
                    <select
                      className="form-select"
                      type="text"
                      // disabled={router.pathname.includes("enrich_data") ? true : false}
                      name="baseDataLevel"
                      value={formik.values.baseDataLevel || ""}
                      onChange={formik.handleChange}
                    >
                      <option>Personal Account</option>
                      <option>Business Account</option>
                      <option>Brick Level</option>
                      <option>Zip Code</option>
                      <option>Others</option>
                    </select>
                  </div>
                  {formik.values.dataSource === "Upload New Data" &&
                    formik.values.baseDataLevel === "Others" && (
                      <div className="col-md-4">
                        <label htmlFor="" className="text-muted">
                          Name of Base Data Level{" "}
                          <span className="text-danger">*</span>
                        </label>
                        <input
                          className="form-control"
                          placeholder="Name of Base Data Level"
                          type="text"
                          name="nameOfBaseDataLevel"
                          value={formik.values.nameOfBaseDataLevel || ""}
                          onChange={formik.handleChange}
                        />
                      </div>
                    )}
                </div>
                <div className="row save-button">
                  <div
                    className={
                      "col-md-12" // : "col-md-6"
                    }
                  >
                    <div className="pull-right">
                      <button
                        type="button"
                        className="btn btn-primary btn-medium mr-1"
                        onClick={formik.handleSubmit}
                      >
                        {"SAVE"}
                      </button>
                      <button
                        type="button"
                        disabled={!formik.values.uniqueResponse.status}
                        className="btn btn-secondary btn-medium"
                      >
                        CANCEL
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* {showfolder && ( */}
            <div className="card">
              <div className="card-body">
                <div style={{ width: "100%", height: "100%" }}>
                  <div style={{ height: 400 }} className="ag-theme-alpine">
                    <AgGridReact
                      treeData={treeData}
                      enableCharts={true}
                      enableRangeSelection={true}
                      defaultColDef={defaultColumnDef}
                      rowData={rowData}
                      columnDefs={columnDefs}
                      stopEditingWhenCellsLoseFocus={true}
                      rowSelection={"multiple"}
                      suppressRowClickSelection={true}
                      singleClickEdit={true}
                      pagination={true}
                      paginationPageSize={20}
                      onGridReady={onGridReady}
                      getDataPath={getDataPath}
                      autoGroupColumnDef={autoGroupColumnDef}
                      // onSelectionChanged={onSelectionChanged}
                      // onCellValueChanged={onCellValueChanged}
                      // onFirstDataRendered={firstDataRenderedHandler}
                      // onModelUpdated={rowCountHandler}
                      sideBar={sideBar}
                    ></AgGridReact>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    </div>
  );
}
